import Link from "next/link";
import { notFound } from "next/navigation";

import { requireActiveAdminId } from "@/features/exams/admin";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ExamStatsPage({ params }: { params: Promise<{ examId: string }> }) {
  await requireActiveAdminId(); const { examId } = await params;
  const exam = await db.exam.findUnique({ where: { id: examId }, select: { id: true, title: true, questions: { select: { id: true, number: true, content: true } }, examLinks: { select: { class: { select: { id: true, name: true, enrollments: { select: { studentId: true } } } } } }, attempts: { where: { submittedAt: { not: null } }, select: { id: true, userId: true, score: true, submittedAt: true, user: { select: { name: true, email: true } }, finalizedAnswers: { select: { questionId: true, isCorrect: true } } }, orderBy: { submittedAt: "desc" } } } });
  if (!exam) notFound();
  const scores = exam.attempts.map((item) => item.score).filter((score): score is number => score !== null).sort((a,b) => a-b);
  const average = scores.length ? scores.reduce((a,b) => a+b,0)/scores.length : null;
  const median = scores.length ? (scores[Math.floor((scores.length-1)/2)] + scores[Math.ceil((scores.length-1)/2)])/2 : null;
  const distribution = [0,2,4,6,8].map((start) => ({ label: `${start}–${start+2}`, count: scores.filter((score) => score >= start && (start === 8 ? score <= 10 : score < start+2)).length }));
  const wrongByQuestion = exam.questions.map((question) => ({ ...question, wrong: exam.attempts.flatMap((attempt) => attempt.finalizedAnswers).filter((answer) => answer.questionId === question.id && !answer.isCorrect).length })).sort((a,b) => b.wrong-a.wrong).slice(0,10);
  return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/admin/de-thi" className="text-sm font-semibold text-navy-400">← Danh sách đề</Link><h1 className="mt-2 text-2xl font-semibold text-navy-600">Thống kê · {exam.title}</h1></div><a href={`/api/admin/exams/${exam.id}/results.csv`} className="rounded-full bg-navy-600 px-5 py-2.5 text-sm font-semibold text-white">Xuất CSV kết quả</a></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[exam.attempts.length,"Lượt nộp"],[new Set(exam.attempts.map((a)=>a.userId)).size,"Học sinh đã làm"],[average?.toFixed(2) ?? "—","Điểm trung bình"],[median?.toFixed(2) ?? "—","Trung vị"]].map(([value,label]) => <div key={label} className="rounded-2xl border border-navy-100 bg-white p-4"><p className="text-2xl font-bold text-navy-600">{value}</p><p className="mt-1 text-xs text-navy-300">{label}</p></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-navy-100 bg-white p-5"><h2 className="font-semibold text-navy-600">Tiến độ theo lớp</h2><div className="mt-4 space-y-3">{exam.examLinks.map(({ class: classroom }) => { const studentIds = new Set(classroom.enrollments.map((e)=>e.studentId)); const done = new Set(exam.attempts.filter((a)=>studentIds.has(a.userId)).map((a)=>a.userId)).size; return <div key={classroom.id}><div className="flex justify-between text-sm text-navy-500"><span>{classroom.name}</span><strong>{done}/{studentIds.size}</strong></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-pastel-100"><div className="h-full bg-navy-400" style={{ width: `${studentIds.size ? done/studentIds.size*100 : 0}%` }} /></div></div>; })}</div></section><section className="rounded-3xl border border-navy-100 bg-white p-5"><h2 className="font-semibold text-navy-600">Phân bố điểm</h2><div className="mt-4 space-y-3">{distribution.map((bucket) => <div key={bucket.label} className="grid grid-cols-[3rem_1fr_2rem] items-center gap-2 text-xs text-navy-400"><span>{bucket.label}</span><div className="h-3 overflow-hidden rounded-full bg-pastel-100"><div className="h-full bg-pastel-600" style={{ width: `${scores.length ? bucket.count/scores.length*100 : 0}%` }} /></div><strong>{bucket.count}</strong></div>)}</div></section></div>
    <section className="rounded-3xl border border-navy-100 bg-white p-5"><h2 className="font-semibold text-navy-600">Câu sai nhiều nhất</h2><div className="mt-4 divide-y divide-navy-50">{wrongByQuestion.map((question) => <div key={question.id} className="flex justify-between gap-4 py-3 text-sm"><span className="text-navy-500">Câu {question.number}. {question.content}</span><strong className="shrink-0 text-red-600">{question.wrong} sai</strong></div>)}</div></section>
    <section className="overflow-hidden rounded-3xl border border-navy-100 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-pastel-50 text-navy-500"><tr><th className="p-3">Học sinh</th><th className="p-3">Email</th><th className="p-3">Điểm</th><th className="p-3">Nộp lúc</th></tr></thead><tbody className="divide-y divide-navy-50">{exam.attempts.map((attempt) => <tr key={attempt.id}><td className="p-3 font-medium text-navy-600">{attempt.user.name}</td><td className="p-3 text-navy-400">{attempt.user.email}</td><td className="p-3 font-semibold">{attempt.score?.toFixed(2) ?? "—"}</td><td className="p-3 text-navy-300">{attempt.submittedAt?.toLocaleString("vi-VN")}</td></tr>)}</tbody></table></div></section>
  </section>;
}
